######################################################################
# adapted from libopencm3, adapted from ve3wwg bluepill book/repo
######################################################################

.PHONY: all rebuild clean clobber elf bin hex srec list images flash debug
# not filenames, but commands for make

PREFIX		?= arm-none-eabi

TOP_DIR 	:= $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
#OPENCM3_DIR 	:= $(abspath $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/libopencm3)
OPENCM3_DIR 	:= $(abspath $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/locm3_lnk)

LIBNAME		= opencm3_stm32f1 # opencm3_stm32f4
DEFS		+= -DSTM32F1 #-DSTM32F4
#defs for libopencm3: otherwise #error "stm32 family not defined."

FP_FLAGS	?= -msoft-float
ARCH_FLAGS	= -mthumb -mcpu=cortex-m3 $(FP_FLAGS) -mfix-cortex-m3-ldrd
ASFLAGS		= -mthumb -mcpu=cortex-m3

#FP_FLAGS	?= -mfloat-abi=hard -mfpu=fpv4-sp-d16
#ARCH_FLAGS	= -mthumb -mcpu=cortex-m4 $(FP_FLAGS)
#ASFLAGS		= -mthumb -mcpu=cortex-m4

CC		:= $(PREFIX)-gcc
#CXX		:= $(PREFIX)-g++ # cpp
LD		:= $(PREFIX)-gcc
AR		:= $(PREFIX)-ar
AS		:= $(PREFIX)-as
OBJCOPY		:= $(PREFIX)-objcopy
SIZE		:= $(PREFIX)-size
OBJDUMP		:= $(PREFIX)-objdump
GDB		:= $(PREFIX)-gdb
OPT		:= -Os -g #-Os = optimize for size -g  = debugging information
#CSTD		?= -std=c99
CSTD		?= -std=gnu99

#TEMP1 		= $(patsubst %.c,%.o,$(SRCFILES))
#TEMP2		= $(patsubst %.asm,%.o,$(TEMP1)) #.asm
#OBJS 		= $(patsubst %.cpp,%.o,$(TEMP2)) # cpp

# srcfiles before incl this file!
OBJS 		:= $(SRCFILES:.c=.o)

LDSCRIPT	?= $(TOP_DIR)/lnk_script.ld

TGT_CFLAGS	+= $(OPT) $(CSTD)
TGT_CFLAGS	+= $(ARCH_FLAGS)
TGT_CFLAGS	+= -Wall -Wundef
TGT_CFLAGS	+= -Wextra -Wshadow -Wimplicit-function-declaration
TGT_CFLAGS	+= -Wredundant-decls -Wmissing-prototypes -Wstrict-prototypes
TGT_CFLAGS	+= -fno-common -ffunction-sections -fdata-sections
TGT_CFLAGS	+= -MD # -MD: GCC dependency-generation option. produces & .d containing info about #incl headers
TGT_CFLAGS	+= $(DEFS)
TGT_CFLAGS	+= -I$(OPENCM3_DIR)/include
#cpp
#TGT_CXXFLAGS	+= $(OPT) $(CXXSTD)
#TGT_CXXFLAGS	+= $(ARCH_FLAGS)
#TGT_CXXFLAGS	+= -Wextra -Wshadow -Wredundant-decls  -Weffc++
#TGT_CXXFLAGS	+= -fno-common -ffunction-sections -fdata-sections
#TGT_CPPFLAGS	+= -MD # -MD moved to TGT_CFLAGS
#TGT_CPPFLAGS	+= -Wall -Wundef
#TGT_CPPFLAGS	+= $(DEFS) # went TGT_CFLAGS
#TGT_CPPFLAGS	+= -I$(OPENCM3_DIR)/include
##TGT_CPPFLAGS	+= -I$(TOP_DIR)/rtos/libwwg/include

TGT_LDFLAGS	+= --static -nostartfiles
TGT_LDFLAGS	+= -T$(LDSCRIPT)
TGT_LDFLAGS	+= $(ARCH_FLAGS)
TGT_LDFLAGS	+= -Wl,-Map=$(*).map
TGT_LDFLAGS	+= -Wl,--gc-sections

LDLIBS		+= -specs=nosys.specs
LDLIBS		+= -Wl,--start-group -lc -lgcc -lnosys -Wl,--end-group
LDLIBS		+= -L$(OPENCM3_DIR)/lib -l$(LIBNAME)

.SUFFIXES:	.elf .bin .hex .srec .list .map .images
.SECONDEXPANSION:
.SECONDARY:

elf:	$(DEPS) $(BINARY).elf
bin:	$(DEPS) $(BINARY).bin
hex:	$(DEPS) $(BINARY).hex
srec:	$(DEPS) $(BINARY).srec
list:	$(DEPS) $(BINARY).list

# Define a helper macro for debugging make errors online
# you can type "make print-OPENCM3_DIR" and it will show you
# how that ended up being resolved by all of the included
# makefiles.
print-%:
	@echo $*=$($*)

%.images: %.bin %.hex %.srec %.list %.map
	@#printf "*** $* images generated ***\n"

%.bin: %.elf
	@#printf "  OBJCOPY $(*).bin\n"
	$(OBJCOPY) -Obinary $(*).elf $(*).bin

%.hex: %.elf
	@#printf "  OBJCOPY $(*).hex\n"
	$(OBJCOPY) -Oihex $(*).elf $(*).hex

%.srec: %.elf
	@#printf "  OBJCOPY $(*).srec\n"
	$(OBJCOPY) -Osrec $(*).elf $(*).srec

%.list: %.elf
	@#printf "  OBJDUMP $(*).list\n"
	$(OBJDUMP) -S $(*).elf > $(*).list

%.elf %.map: $(OBJS) $(LDSCRIPT)
	$(LD) $(TGT_LDFLAGS) $(LDFLAGS) $(OBJS) $(LDLIBS) -o $(*).elf
	$(SIZE) $(BINARY).elf

%.o: %.c
	@#printf "  CC      $(*).c\n"
	$(CC) $(TGT_CFLAGS) $(CFLAGS) -o $(*).o -c $(*).c
#$(CC) $(TGT_CFLAGS) $(CFLAGS) $(TGT_CPPFLAGS) $(CPPFLAGS) -o $(*).o -c $(*).c # cpp

# cpp + asm
#%.o: %.cxx
#	@#printf "  CXX     $(*).cxx\n"
#	$(CXX) $(TGT_CXXFLAGS) $(CXXFLAGS) $(TGT_CPPFLAGS) $(CPPFLAGS) -o $(*).o -c $(*).cxx
#
#%.o: %.cpp
#	@#printf "  CXX     $(*).cpp\n"
#	$(CXX) $(TGT_CXXFLAGS) $(CXXFLAGS) $(TGT_CPPFLAGS) $(CPPFLAGS) -o $(*).o -c $(*).cpp
#
#%.o: %.asm
#	$(AS) $(ASFLAGS) -o $*.o -c $<

clean:
	@#printf "  CLEAN\n"
	$(RM) *.o *.d generated.* $(OBJS) $(patsubst %.o,%.d,$(OBJS))

clobber: clean
	rm -f *.elf *.bin *.hex *.srec *.list *.map $(CLOBBER)

flash: $(BINARY).elf
	$(GDB) $< \
		-ex "target extended-remote :3333" \
		-ex "load" \
		-ex "monitor reset" \
		-ex "detach" \
		-ex "quit"
#monitor reset XOR break main , continue
debug: $(BINARY).elf
	$(GDB) $< -ex "target extended-remote :3333" -ex "load"

-include $(OBJS:.o=.d)
# Include GCC-generated dependency files.
# -MD causes GCC to generate the .d files.
# Make uses those dependencies + file timestamps to decide what needs rebuilding.
# The leading '-' means missing .d files are not an error on the first build.


# End
